[package]
name = "chord-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chord-cli"
path = "src/main.rs"

[dependencies]
chord-processor = { path = "../rust" }
tree-sitter = "0.20"
tree-sitter-chordprog = { path = "../../tree-sitter-chordprog" }
serde_json = "1.0"
